fix: 📌 Removed unused variable `parent` in sample code in Minimum Example
There is an unused variable `parent` in the sample code `packages/compiler-core/parse.ts` in the Minimum Example,
The following type check error occurs, so I removed it from the sample code and the documentation.

``sh
... /... /packages/compiler-core/parse.ts:201:9 - error TS6133: 'parent' is declared but its value is never read.

201 const parent = last(ancestors)
            ~~~~~~
```