fix: 📌 Removed unused `Data` in sample code in Minimum Example
There is an unused `Data` in the sample code `packages/runtime-core/componentOptions.ts` in the Minimum Example,
The following type check error occurs, so I removed it from the sample code.

```sh
../../packages/runtime-core/componentOptions.ts:1:1 - error TS6133: 'Data' is declared but its value is never read.

1 import { Data } from './component'
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```