fix: 📌 Remove unused `parent` in sample codes.
There is an unused `parent` in the sample code `packages/compiler-core/parse.ts`,
The following type check error occurs, so I removed it from the sample code.

```sh
../../packages/compiler-core/parse.ts:201:9 - error TS6133: 'parent' is declared but its value is never read.

201   const parent = last(ancestors)
```